# Generated by Django 3.0.6 on 2020-05-14 09:05

import Recipe_Core_App.models.recipe
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_Core_App', '0006_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=Recipe_Core_App.models.recipe.recipe_image_file_path),
        ),
    ]
